sudo: false
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3

branches:
  only:
    - master
    - develop

before_install: gem install bundler

script:
    - bundle exec rspec --order=random

matrix:
  include:
    - rvm: ruby-head
      script: bundle exec rubocop
